sudo: required

# Install jq
addons:
  apt:
    packages:
    - jq

install:
  - sudo pip install ansible ansible-lint
  - gem install awesome_bot
  - TERRAFORM_LATEST_VERSION=$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')
  - curl --silent --location https://releases.hashicorp.com/terraform/${TERRAFORM_LATEST_VERSION}/terraform_${TERRAFORM_LATEST_VERSION}_linux_amd64.zip --output /tmp/terraform_linux_amd64.zip
  - sudo unzip -o /tmp/terraform_linux_amd64.zip -d /usr/local/bin/

script:
  #- test -f $HOME/.ssh/id_rsa || ( install -m 0700 -d $HOME/.ssh && ssh-keygen -b 2048 -t rsa -f $HOME/.ssh/id_rsa -q -N "" )
  - terraform init ansible/terraform/openstack
  - terraform validate -check-variables=false ansible/terraform/openstack
  - terraform init ansible/terraform/azure
  - terraform validate -check-variables=false ansible/terraform/azure
  - awesome_bot --white-list "$" --allow-dupe --allow-redirect --skip-save-results `find . -name *.md`
  - ansible-lint -x ANSIBLE0004 ansible/site.yml
  - sed -i 's/.*secrets.yml.*/#&/' ansible/site.yml
  - ansible-playbook --syntax-check ansible/site.yml

notifications:
  slack: miracloud:qPdiQJMHmCsxhpR6QTT4yr98
