- name: Create disk file
  command: qemu-img create -f qcow2 -o size=5G /var/lib/libvirt/images/{{ item }}.qcow2
  args:
    creates: /var/lib/libvirt/images/{{ item }}.qcow2
  with_sequence: start=1 end={{ sub_vms_count }} format=vm-pxe%01x-{{ ansible_hostname }}

- name: Set correct owner/group for the qcow2 disk image
  file:
    path: /var/lib/libvirt/images/{{ item }}.qcow2
    owner: libvirt-qemu
    group: kvm
  with_sequence: start=1 end={{ sub_vms_count }} format=vm-pxe%01x-{{ ansible_hostname }}

- name: Get list of vms
  virt:
    command: list_vms
  register: virt_vms

- name: Define empty virtual machine to boot from network
  virt:
    name: "{{ item }}"
    autostart: yes
    command: define
    xml: "{{ lookup('template', 'templates/vm-template.xml.j2') }}"
  when: item not in virt_vms.list_vms
  with_sequence: start=1 end={{ sub_vms_count }} format=vm-pxe%01x-{{ ansible_hostname }}
