- name: Create directory /var/lib/libvirt/images/cfg01/
  file:
    path: /var/lib/libvirt/images/cfg01
    state: directory

- name: Download VM image
  get_url:
    url: "{{ cfg01_image_url }}"
    dest: /var/lib/libvirt/images/cfg01/cfg01-day01.qcow2

- name: Download define script
  get_url:
    url: "{{ cfg01_define_script_url }}"
    dest: /root/define-vm.sh
    mode: 0755

# - name: Define the cfg01 VM
#   command: /root/define-vm.sh
#   environment:
#     VM_NAME: "{{ cfg01_vm_name }}"
#     VM_SOURCE_DISK: "{{ cfg01_vm_source_disk }}"
#     VM_CONFIG_DISK: "{{ cfg01_vm_config_disk }}"
#     VM_MGM_BRIDGE_NAME: "{{ cfg01_vm_mgm_bridge_name }}"
#     VM_CTL_BRIDGE_NAME: "{{ cfg01_vm_ctl_bridge_name }}"
#     VM_MEM_KB: "{{ cfg01_vm_mem_kb }}"
#     VM_CPUS: "{{ cfg01_vm_cpus }}"
#   creates: "{{ cfg01_vm_name }}-vm.xml"
#   register: define_vm_output
#   changed_when: define_vm_output | search('rendered VM config')
