- name: Save terrafrom variables to file
  template:
    src: templates/terraform.tfvars.j2
    dest: terraform/{{ cloud_platform }}/terraform.tfvars

- name: Change infrastructure using terraform (this may take a long time...)
  terraform:
    state: "{{ terraform_state }}"
    project_path: terraform/{{ cloud_platform }}/
  register: terraform_apply_output

- name: Add hosts created by terraform and wait for boot to complete
  block:
  - name: Add hosts created by terraform
    add_host:
      name: "{{ item.1 }}"
      ansible_host: "{{ item.0 }}"
      groups:
        - training-lab-{{ item.1.split('.')[1] }}
        - training-lab
    loop: "{{ terraform_apply_output.outputs.vm_public_ip.value|zip(terraform_apply_output.outputs.vm_name.value)|list }}"
    changed_when: false

  - name: Wait for all VMs to boot
    wait_for:
      host: "{{ item }}"
      port: "22"
      search_regex: OpenSSH
      delay: 1
    loop: "{{ terraform_apply_output.outputs.vm_public_ip.value }}"
  when: terraform_apply_output.state == 'present'
