---
- name: Use terraform to chnage the infrastructure
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vars/secrets.yml

  tasks:
    - include_tasks: tasks/terraform.yml


- name: Configure VMs created by terraform
  hosts: terraform
  user: "{{ default_username }}"
  become: true

  tasks:
    - include_tasks: tasks/configure_vm.yml

    - include_tasks: tasks/kvm01.yml
      when: ansible_hostname is search('kvm01')

  handlers:
    - name: restart libvirt
      service:
        name: libvirtd
        enabled: yes
        state: restarted

    - name: reload networking
      service:
        name: networking
        state: restarted

    - name: reload ufw
      service:
        name: ufw
        state: restarted

