---
########################################################################
# Build Cloud infrastructure
########################################################################
- name: Define the infrastructure
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vars/secrets.yml
    - vars/{{ cloud_platform }}_secrets.yml

  tasks:
    - import_tasks: tasks/terraform.yml


########################################################################
# Configure all Virtual Machines
########################################################################
- name: Configure VMs created by terraform
  hosts: training_lab
  user: "{{ default_username }}"
  become: true

  vars_files:
    - vars/secrets.yml
    - vars/{{ cloud_platform }}_secrets.yml

  tasks:
    - import_tasks: tasks/configure_vms.yml
    - import_tasks: tasks/define_vms.yml
      when: ansible_fqdn in groups['training_lab_kvm']

  handlers:
    - import_tasks: handlers/handlers.yml


########################################################################
# Configure kvm01 Virtual Machines
########################################################################
- name: Configure kvm01 VMs
  hosts: training_lab_kvm01
  user: "{{ default_username }}"
  become: true

  vars_files:
    - vars/secrets.yml
    - vars/{{ cloud_platform }}_secrets.yml

  tasks:
    - import_tasks: tasks/kvm01.yml

  handlers:
    - import_tasks: handlers/handlers.yml
