---
- name: Use terraform to chnage the infrastructure
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vars/secrets.yml
    - vars/{{ cloud_platform }}_secrets.yml

  tasks:
    - include_tasks: tasks/terraform.yml


- name: Configure VMs created by terraform
  hosts: terraform
  user: "{{ default_username }}"
  become: true

  tasks:
    - include_tasks: tasks/configure_vm.yml

    - debug: var=ansible_hostname
      when: ansible_hostname is search('kvm01')

    - include_tasks: tasks/kvm01.yml
      when: ansible_hostname is search('kvm01')

    - name: Wait for user imput to continue
      pause:
        prompt: "Configure MAAS (http://{{ inventory_hostname }}/MAAS), then press ENTER"
      when: ansible_hostname is search('kvm01')

    - include_tasks: tasks/run_vm.yml

    - name: Display all "external" URLs
      debug:
        msg:
          - "MAAS   : http://{{ inventory_hostname }}/MAAS"
          - "Jenkins: http://{{ inventory_hostname }}:8081"
          - "noVNC  : https://{{ inventory_hostname }}/vnc.html?port=443&true_color=1&password={{ student_password }}"
          - "VNC    : vnc://{{ inventory_hostname }}:5901"
      when: ansible_hostname is search('kvm01')

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes

    - name: restart libvirt
      service:
        name: libvirtd
        enabled: yes
        state: restarted

    - name: restart networking
      service:
        name: networking
        state: restarted

    - name: restart novnc
      service:
        name: novnc
        state: restarted

    - name: restart sshd
      service:
        name: sshd
        state: restarted

    - name: restart ufw
      service:
        name: ufw
        state: restarted

